name: syndirella
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pandas
  - numpy
  - glob2
  - rdkit==2023.09.5
  - requests
  - pillow
  - fragmenstein
  - shortuuid
  - jupyter
  - biopython